blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/MAlkabbani/RCal/security/policy
    about: Please follow private reporting instructions for vulnerabilities.
